[package]
authors = ["oleiade <theo@crevon.me>"]
edition = "2018"
license = "MIT"
name = "jackdauer"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nom = "6"
